package com.nyamnyam.coach.boss.entity;

public enum BossConditionTargetType {
    DIET_RECORD_MEMBER_COUNT,
    DIET_RECORD_COUNT,
    NUTRITION_GOAL_ACHIEVEMENT,
    QUEST_COMPLETION_COUNT,
    SUGAR_UNDER_LIMIT,
    PROCESSED_DRINK_ZERO,
    VEGETABLE_VARIETY
}
